### ISSUE TITLE
[REFACTOR] 마무리 작업

### ISSUE THREAD

**Issue by WinterHana** [WinterHana/Promote_Project#19]
**Description**
============
이슈를 다 해결하고 마무리 작업 리스트입니다.
남은 이슈들은 조만간 다 해결할 예정...!(밤 세가면서 작업할거임)

**Todo List**
============
- [ ] 메인 화면 만들기
- [ ] 메인 화면을 빗된 UI 하나 만들기(멈춤, 종료 등)
- [ ] 빌드 후 테스트 -> 다음 이슈로 넘어감

**ETC**
============
이 이슈들이 완전히 해결되면 진행할 예정입니다.
#7 
#8 
#14 
#16
