### ISSUE TITLE
[fix] 피드백 받은 버그 수정

### ISSUE THREAD

**Issue by WinterHana** [WinterHana/Promote_Project#22]
**Description**
============
피드백 받은 버그들을 수정합니다.

**Todo List**
============
- [x] 캐릭터 물리 관련 오류 : 적을 밀쳐낼 수 있는거 뭐지? -> 적의 무게를 조절해서 해결
- [x] 사다리 조작감 개선

위 두가지는 #8 과 연관지어 보는 중입니다.

- [x] 대화창 오타 수정
- [x] 스테이러스 남은 돈이 -가 되는 버그 수정
- [x] X키 상호작용 할 때 연타가 되는 현상 -> 선택 중에 플레이어가 움직이는 것이 좀 어색해서 그것을 기준으로 수정
- [x] 플레이어가 적 머리 위로 올라가면 적이 고장남
- [x] "엔딩을 보시겠습니까?" 에서 X를 눌러도 엔딩으로 넘어감 -> 원래 의도된 사항이라서 안내 문구를 추가했음
- [ ] 두번째 발판을 없앨 때 X 두 번 두르면 스프라이트가 남아있음
- [x] 키를 계속 누르면 벽에 붙어서 갈 수 있는 버그 수정 : 마찰력 조절

230604 수정
- [x] 갑자기 넉백이 안되는 현상 수정

**ETC**
============
<밸런스 조절 사항>
- [x] 전환 후 체력 회복량 감소 50 - > 30
- [x] 적 피격 시 대미지를 입도록 조절 : 데미지 10
- [x] 플레이어 무적 시간 조절 : 2초 -> 1초

<기타 수정 사항>
- [x] 스테이러스 줄 간격 조절
- [x] 플레이어 콜라이더 크기 조금 작게 조절
