### ISSUE TITLE
[FEATURE] 적 AI 개선 및 액션 상호작용 작성하기

### ISSUE THREAD

**Issue by WinterHana** [WinterHana/Promote_Project#7]
**Description**
============
적 AI 개선 및 액션 상호작용 작성하기

**Todo List**
============
- [x] 적 AI 개선
- [x] 적 에셋 찾고 애니매이션 적용
- [x] 공격 상호작용 작성
- [x] 플레이어 피격 및 공격 구현하기

**ETC**
============
