### ISSUE TITLE
[FIX] 플레이어 움직임 관련 버그 이슈

### ISSUE THREAD

**Issue by WinterHana** [WinterHana/Promote_Project#8]
**Description**
============
플레이어 움직임 관련 내용입니다.

**Todo List**
============
- [ ] 어느 커맨드를 사용하면 앉은 상태로 빠르게 이동 가능함
- [ ] 마찬가지로 어떤 상황에서 일어선 상태로 느리게 이동 가능함
- [x] 사다리 조작감 관련 이슈 -> 좀 더 인식을 잘 하도록 알고리즘 개선하기 -> 콜라이더를 이용해서 반응하도록 개선
- [x] 좀 더 역동적인 움직임이 가능하도록 조정하기 -> 중력, 무게 등 수치 조절

**ETC**
============
피드백 과정에서 고칠 예정입니다.
